#!/usr/bin/env bash
# Render (and optionally publish) THIS deployment's relay page.
#
# The relay page ships as a generic template (relay/index.template.html). Every
# deployment substitutes its own Duck DNS name, panel port and Pages URL here, so
# no personal configuration ever lives in the repository. The rendered site and
# the panel-side relay URL (public/js/relay-config.js) are generated artifacts
# and are gitignored.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATE="$PROJECT_DIR/relay/index.template.html"
CONFIG="${DUCKDNS_CONFIG:-$HOME/.config/tmux-web-panel/duckdns.env}"
SITE_DIR="${RELAY_SITE_DIR:-$HOME/.config/tmux-web-panel/relay-site}"
CA_CRT="$HOME/.config/tmux-web-panel/ca/ca.crt"
PORT="${PANEL_PORT:-7681}"
PUBLISH=0
[[ "${1:-}" == "--publish" ]] && PUBLISH=1

usage() {
  cat <<EOF
Usage: $0 [--publish]

Renders relay/index.template.html with this deployment's values into
$SITE_DIR, and writes public/js/relay-config.js so the login page knows
where to bounce relayed logins. With --publish it also creates the GitHub
Pages repository (needs the gh CLI, logged in) and pushes the rendered site.

Environment:
  DUCKDNS_DOMAIN  Duck DNS subdomain (falls back to $CONFIG)
  PANEL_PORT      Panel HTTPS port (default: 7681)
  PAGES_URL       Pages base URL, e.g. https://YOU.github.io/relay/  (required)
  RELAY_SITE_DIR  Render output dir (default: $SITE_DIR)

Example:
  DUCKDNS_DOMAIN=mybox PAGES_URL=https://me.github.io/mybox-relay/ $0 --publish
EOF
  exit 1
}

[[ -f "$TEMPLATE" ]] || { echo "Error: missing template $TEMPLATE" >&2; exit 1; }

if [[ -r "$CONFIG" ]]; then
  # shellcheck source=/dev/null
  set -a; . "$CONFIG"; set +a
fi
: "${DUCKDNS_DOMAIN:?set DUCKDNS_DOMAIN (or put it in $CONFIG)}"
: "${PAGES_URL:?set PAGES_URL, e.g. https://YOU.github.io/relay/}"
case "$PAGES_URL" in */) ;; *) PAGES_URL="$PAGES_URL/";; esac

mkdir -p "$SITE_DIR"
sed -e "s|__DUCKDNS_FQDN__|${DUCKDNS_DOMAIN}.duckdns.org|g" \
    -e "s|__PANEL_PORT__|${PORT}|g" \
    "$TEMPLATE" > "$SITE_DIR/index.html"
cp "$PROJECT_DIR/relay/robots.txt" "$SITE_DIR/robots.txt"
if [[ -r "$CA_CRT" ]]; then
  cp "$CA_CRT" "$SITE_DIR/ca.crt"
else
  echo "⚠ no CA cert at $CA_CRT — the page's download link will 404 until local-ca.sh runs"
fi

# Panel-side config: where relayed logins bounce back to. Gitignored.
cat > "$PROJECT_DIR/public/js/relay-config.js" <<CFG
// Generated by scripts/setup-relay.sh — do not commit; see relay-config.example.js.
window.PANEL_RELAY_PAGE = '${PAGES_URL}';
CFG

echo "✓ Rendered relay site → $SITE_DIR"
echo "✓ Wrote public/js/relay-config.js → $PAGES_URL"

if [[ "$PUBLISH" == 1 ]]; then
  command -v gh >/dev/null || { echo "Error: --publish needs the gh CLI" >&2; exit 1; }
  repo="$(printf '%s' "$PAGES_URL" | sed -n 's|https://\([^/]*\)\.github\.io/\([^/]*\)/.*|\1/\2|p')"
  [[ -n "$repo" ]] || { echo "Error: PAGES_URL must look like https://USER.github.io/REPO/" >&2; exit 1; }
  gh repo view "$repo" >/dev/null 2>&1 || gh repo create "$repo" --public >/dev/null
  cd "$SITE_DIR"
  [[ -d .git ]] || git init -q -b main
  git remote get-url origin >/dev/null 2>&1 || git remote add origin "git@github.com:${repo}.git"
  git add -A
  git -c user.name="${GIT_AUTHOR_NAME:-relay-setup}" -c user.email="${GIT_AUTHOR_EMAIL:-relay-setup@localhost}" \
    commit -q -m "Render relay page for ${DUCKDNS_DOMAIN}" || echo "(no changes to commit)"
  git push -q -u origin main
  gh api -X POST "repos/${repo}/pages" -f 'source[branch]=main' -f 'source[path]=/' >/dev/null 2>&1 \
    || echo "(Pages already enabled or needs a moment)"
  echo "✓ Published to $PAGES_URL (Pages build takes ~1 min, edge cache ~10 min)"
fi

echo ""
echo "Next: scripts/install-lan-ip-sync.sh install   (publishes the IP + keeps the cert current)"
